### ISSUE TITLE
Update documentation for Socket mode in Slack

### ISSUE THREAD

**Issue by theothertomelliott** [getgort/getgort.github.io#3]
Now that Gort supports Socket mode in Slack, the documentation will need to be updated to reflect the changes to expected API keys and how to create a Slack app using the manifest.

**Comment by clockworksoul** [comment]
Would you say that the changes you made to the [quickstart](https://github.com/getgort/getgort.github.io/blob/main/quickstart.md) page are sufficient to cover this, or are you thinking something more comprehensive?

**Comment by theothertomelliott** [comment]
I think the quickstart update should do the trick at least for the time being. Closing.
